### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by Draxxx** [eduardomota/other-rtl2832u-driver#1]
Do you have a current / signed / WQHL / working driver for Windows 10/11? 
Or are you just posting REALTEK's last driver?

**Comment by supermarsx** [comment]
This is the driver i found that worked on Windows 10/11 with rtl2832 dongles from ebay, is it not working for you?

**Comment by Draxxx** [comment]
These drivers DONOT work under Win10/11 with Memory Integrity / Core
Isolation activated.

**Comment by supermarsx** [comment]
Honestly havent used that thing for years now, i've posted this repo as mirror mostly for myself. Only other options i'll suggest is looking elsewhere for another driver, sign and/or build a driver from scratch, use the sdr dongle on an android with OTG (also used to do it and works just fine), open an android emulator and pass through the sdr to the vm.

**Comment by Draxxx** [comment]
Fair enough. Apologies.
I've been hunting for a compatible driver for too long. RealTek are
frustratingly unresponsive, and it is beyond my ability to build a new
driver.
I need it for a PCI card.
Thanks anyway.
